package org.neodatis.odb.ant.vo2.meta;

/**

Attribute information of class org.neodatis.odb.ant.vo2.Vo2

 generated by NeoDatis on  Tue Jan 18 13:56:23 BRST 2011

*/
public class Vo2Meta{
	public final static String I = "i";
}