package org.neodatis.odb.ant.vo.meta;

/**

Attribute information of class org.neodatis.odb.ant.vo.Vo1

 generated by NeoDatis on  Tue Jan 18 13:57:17 BRST 2011

*/
public class Vo1Meta{
	public final static String NAME = "name";
	public final static String AGE = "age";
	public final static String VALUE_TO_ADD = "valueToAdd";
}